blueprint:
  name: Z2M - EnOcean PTM 215Z FoH switch - Advanced
  description: Controller automation for executing actions triggered by EnOcean PTM 215Z FoH (Friends of Hue) switch. 
    Make sure that 'Elapsed' is enabled in the z2m advanced settings.
use_blueprint:
  path: zdralic/EnOcean PTM 215Z - Advanced.yaml
  input:
    controller: bar_foh_switch
    button_1_pressed:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.zdralic_main
    button_1_held:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/zdralic_main/set
          payload: "{\"brightness_move_onoff\": 51}"
          qos: 0
          retain: false
    button_1_released:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/zdralic_main/set
          payload: "{\"brightness_move\": \"stop\"}"
          qos: 0
          retain: false
    button_2_pressed: []
    button_2_held: []
    button_2_released: []
    button_3_pressed:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.zdralic_main
    button_3_held:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/zdralic_main/set
          payload: "{\"brightness_move_onoff\": -51}"
          qos: 0
          retain: false
    button_3_released:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/zdralic_main/set
          payload: "{\"brightness_move\": \"stop\"}"
          qos: 0
          retain: false
